.github/workflows/lint-test.yaml, charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml, charts/datahub/templates/elasticsearch-setup-job.yml, charts/prerequisites/Chart.yaml
Update frontend SSL env variables and add index prefix variables to applicable deploys.
=> Update frontend SSL env variables for product analytics

.github/workflows/lint-test.yaml, .github/workflows/release.yaml, charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/subcharts/datahub-frontend/README.md, charts/datahub/subcharts/datahub-frontend/values.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-ingestion-cron/README.md, charts/datahub/subcharts/datahub-ingestion-cron/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/README.md, charts/datahub/subcharts/datahub-mae-consumer/values.yaml, charts/datahub/subcharts/datahub-mce-consumer/README.md, charts/datahub/subcharts/datahub-mce-consumer/values.yaml, charts/datahub/values.yaml
Upgrade to v0.8.6 Release notes: https://github.com/linkedin/datahub/releases/tag/v0.8.6
Changing the image tags of subcharts to head, so we don't have to change it every time.
=> feat(upgrade): Upgrade to v0.8.6

charts/datahub/Chart.yaml
Upgrade helm version to update index.yaml.
=> feat(upgrade): Upgrade version

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml
=> fix(upgrade): Add SSL secrets to upgrade jobs

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml, charts/datahub/templates/elasticsearch-setup-job.yml, charts/datahub/templates/kafka-setup-job.yml, charts/datahub/templates/mysql-setup-job.yml
This is needed to install datahub into more secure/controlled kubernetes clusters.
=> feat: Add k8s node config & init container support

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml, charts/datahub/values.yaml
Need to add entity registry path to all pods that depend on entity service
=> feat(upgrade): Upgrade to v0.8.7

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
=> feat(upgrade): Upgrade to v0.8.8

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/values.yaml
Add support for AWS glue registry
=> feat(upgrade): Upgrade to v0.8.9

charts/datahub/Chart.yaml, charts/datahub/templates/kafka-setup-job.yml
=> fix(kafka-setup): Fix kafka setup job

.gitignore, charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml
Fixed typo causing extraInitContainers under datahubUpgrade to be missed.
=> fix(datahub-upgrade): Fix extraInitContainers

charts/datahub/Chart.yaml, charts/datahub/templates/kafka-setup-job.yml, charts/datahub/values.yaml
For default setup, it can only take one as the value.
=> fix(kafka-setup): Rollback replication factor / partitions change

charts/datahub/Chart.yaml, charts/datahub/templates/kafka-setup-job.yml
Fix issue when partitions are set
=> fix(kafka-setup): Fix partitions variable

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
https://github.com/linkedin/datahub/releases/tag/v0.8.12
=> feat(upgrade): Upgrade to v0.8.12

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
https://github.com/linkedin/datahub/releases/tag/v0.8.13
=> feat(upgrade): Upgrade to v0.8.13

.github/ISSUE_TEMPLATE/--bug-report.md, .github/ISSUE_TEMPLATE/--feature-request.md, .github/ISSUE_TEMPLATE/--question.md, .github/pull_request_template.md
Add PR and issue templates that are consistent with those of datahub
=> feat(dev-ops) Add PR and issue templates

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/_helpers.tpl, charts/datahub/subcharts/datahub-frontend/templates/ingress.yaml, charts/datahub/subcharts/datahub-gms/templates/_helpers.tpl, charts/datahub/subcharts/datahub-gms/templates/ingress.yaml
=> New ingress class since k8s v1.22

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
Release notes: https://github.com/linkedin/datahub/releases/tag/v0.8.16
=> feat(upgrade): Upgrade to v0.8.16

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
Release notes: https://github.com/linkedin/datahub/releases/tag/v0.8.17
=> feat(upgrade): Upgrade to v0.8.17

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
Release notes: https://github.com/linkedin/datahub/releases/tag/v0.8.18
=> feat(upgrade): Upgrade to v0.8.18

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
Release notes: https://github.com/linkedin/datahub/releases/tag/v0.8.19
=> Upgrade to 0.8.19

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/values.yaml
=> Expose jmx

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
=> Upgrade to 0.8.20

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
=> upgrade to 0.8.21

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
=> add helm charts for 0.8.22

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/ingress.yaml, charts/datahub/subcharts/datahub-frontend/templates/service.yaml, charts/datahub/subcharts/datahub-frontend/values.yaml, charts/datahub/subcharts/datahub-gms/templates/ingress.yaml, charts/datahub/subcharts/datahub-gms/templates/service.yaml, charts/datahub/subcharts/datahub-gms/values.yaml
=> Added possibility to set Ingress spec from values file instead of hardcoded values.

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/README.md, charts/datahub/subcharts/datahub-frontend/templates/service.yaml, charts/datahub/subcharts/datahub-frontend/values.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-gms/templates/service.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/README.md, charts/datahub/subcharts/datahub-mae-consumer/templates/service.yaml, charts/datahub/subcharts/datahub-mae-consumer/values.yaml, charts/datahub/values.yaml
=> Add NodePort support for datahub-frontend, datahub-gms and datahub-mae-consumer

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml
Looks like these were updated https://github.com/linkedin/datahub/blob/master/metadata-service/factories/src/main/java/com/linkedin/gms/factory/entity/RestliEntityClientFactory.java#L17-L21, in https://github.com/linkedin/datahub/pull/3675. Had to update them in my deployment to work!
=> fix(consumer jobs): Fix MAE and MCE env vars to connecting to GMS

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
=> feat(upgrade) Upgrade to v0.8.23

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
=> feat(upgrade): Upgrade to v0.8.24

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
=> release(0.8.25): upgrade to release 0.8.25

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
=> Upgrade to 0.8.26

charts/datahub/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml
=> fix indentation in actions container

charts/datahub/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/values.yaml, charts/datahub/subcharts/datahub-frontend/values.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-ingestion-cron/README.md, charts/datahub/subcharts/datahub-ingestion-cron/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/values.yaml, charts/datahub/subcharts/datahub-mce-consumer/values.yaml, charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml, charts/datahub/templates/elasticsearch-setup-job.yml, charts/datahub/templates/kafka-setup-job.yml, charts/datahub/templates/mysql-setup-job.yml
=> change pull policy to reduce rate limit errors

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-without-neo4j.yaml, charts/datahub/quickstart-values.yaml, charts/datahub/values.yaml
Release notes: https://github.com/linkedin/datahub/releases/tag/v0.8.27
=> feat(upgrade): Upgrade to v0.8.27

charts/datahub/Chart.yaml
=> fix(version): Up app version

charts/datahub/Chart.yaml, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/values.yaml
=> update CLI versions

charts/datahub/Chart.yaml, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/acryl-datahub-actions/README.md, charts/datahub/subcharts/acryl-datahub-actions/values.yaml, charts/datahub/values.yaml
=> revert version due to regression

charts/datahub/Chart.yaml, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/acryl-datahub-actions/README.md, charts/datahub/subcharts/acryl-datahub-actions/values.yaml, charts/datahub/values.yaml
=> update actions image tag

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/values.yaml
=> Helm release for v0.8.30

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/values.yaml
=> feat(upgrade): Update to v0.8.31

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/values.yaml
=> feat(enable-cache): Add enable cache flag

charts/datahub/Chart.yaml
=> fix(chart): bump version

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml, charts/datahub/values.yaml
=> feat(upgrade): Helm release for v0.8.32

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml, charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml, charts/datahub/templates/_helpers.tpl, charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
=> fix(cronjob) Fixes cron job helper scopes that computes capabilities

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/values.yaml
Check out the release notes here https://github.com/datahub-project/datahub/releases/tag/v0.8.33
=> feat(release): Upgrade to v0.8.33

charts/datahub/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml, charts/datahub/templates/kafka-setup-job.yml
=> bugfix:Added quotes to fix helm template parsing issues

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/values.yaml
=> update helm charts for v0.8.34

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/values.yaml
=> Bumping datahub version to 0.8.36

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-auth-secrets.yml, charts/datahub/templates/datahub-encryption-secrets.yml
=> refactor(secrets): use generic approach to reuse existing secret keys

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/values.yaml
Title says it!
Helm Charts for 0.8.38 hot off the press!
=> Bumping helm chart for DataHub v0.8.38

charts/datahub/Chart.yaml, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/values.yaml
=> fix(charts): use the same image in values.yaml as in the acryl-datahub-actions subchart

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/acryl-datahub-actions/README.md, charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/values.yaml
=> add new variables, update default CLI to use the variables

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/values.yaml
=> Upgrade to v0.8.39

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/values.yaml
=> upgrading to 8.40

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/values.yaml
=> update to v0.8.41

charts/prerequisites/Chart.yaml
=> fix(mysql): update mysql helm chart version

charts/prerequisites/Chart.yaml
=> fix(kafka): update kafka chart version

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-frontend/README.md, charts/datahub/subcharts/datahub-frontend/values.yaml, charts/datahub/subcharts/datahub-mce-consumer/values.yaml, charts/datahub/values.yaml, charts/prerequisites/Chart.yaml
Also fixes MCE consumer default values from PR: https://github.com/acryldata/datahub-helm/pull/123 and missing docs from: https://github.com/acryldata/datahub-helm/pull/141
=> Update to v0.8.43

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml, charts/datahub/values.yaml
=> feat(upgrade): allow setting batch args

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/values.yaml
=> release: Bumping to v0.8.44 for release

.github/workflows/close-stale-issues.yml
=> feat(ci): close stale issues/prs

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> fix(monitoring): Fixes monitoring default values + gms chart version

charts/datahub/Chart.yaml, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/README.md, charts/datahub/values.yaml
=> chore: bump datahub-actions version

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
=> feat(monitoring): enable monitoring on frontend

charts/datahub/Chart.yaml, charts/datahub/values.yaml
**Add kafka-exporter to expose prometheus metrics for kafka cluster**
=> Add kafka-exporter to expose prometheus metrics for kafka cluster

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-frontend/values.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/values.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/templates/datahub-upgrade/_upgrade.tpl, charts/datahub/templates/elasticsearch-setup-job.yml, charts/datahub/values.yaml
Complementing https://github.com/datahub-project/datahub/pull/5887 to introduce insecure curl connectivity option.
=> feat(elasticsearch-setup): Add support for insecure curl connections

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/values.yaml
=> bumping helm charts for 0.8.45

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-frontend/values.yaml
=> fix(datahub-frontend): Remove unused env var

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/values.yaml
=> feat(release): change default datahub versions to 0.9.0

.github/workflows/release.yaml
=> fix(CI): remove duplicate id

.github/scripts/bump-chart-versions.sh, .github/workflows/release.yaml
=> fix(ci): us sh instead of bash; increase tag by patch

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/values.yaml
Bumping those final 2.110 to 2.111.
=> Fix v0.9.1 release versions

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/values.yaml
Title says it. Bumping the container version per the release process!
=> release(v0.9.2) Release Helm Charts for DataHub v0.9.2

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
=> fix(gha): revert auto bump release changes

charts/datahub/subcharts/datahub-frontend/README.md, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-mae-consumer/README.md, charts/datahub/subcharts/datahub-mce-consumer/README.md
=> fix(doc): correct doc for serviceMonitor.create

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/values.yaml
=> release(v0.9.3): Bumping charts to v0.9.3

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-frontend/values.yaml
It fixes wrong definition of lifecycle template according in values.yaml
=> Fix lifecycle templating for frontend

charts/datahub/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml, charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml, charts/datahub/templates/elasticsearch-setup-job.yml, charts/datahub/templates/kafka-setup-job.yml, charts/datahub/templates/mysql-setup-job.yml, charts/datahub/templates/postgresql-setup-job.yml, charts/datahub/values.yaml
=> feat(global-version): add option to globally define versions

charts/prerequisites/Chart.yaml
=> Update versions & bitnami index

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> fix: add extra space before comment to make yamllint pass

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/values.yaml, charts/datahub/templates/datahub-upgrade/datahub-build-indices-job.yml, charts/datahub/values.yaml
=> feat(elasticsearch): adding elasticsearch index job

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/templates/datahub-upgrade/datahub-build-indices-job.yml, charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml, charts/datahub/templates/elasticsearch-setup-job.yml, charts/datahub/templates/kafka-setup-job.yml, charts/datahub/templates/mysql-setup-job.yml, charts/datahub/templates/postgresql-setup-job.yml, charts/datahub/values.yaml
Also updates helm chart to deploy DataHub v0.9.6 & removes hardcoded tag version for datahub upgrade job.
=> fix(jobs): Make job pull policy consistent with subchart

charts/datahub/Chart.yaml, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/values.yaml, charts/datahub/values.yaml, charts/prerequisites/Chart.yaml, charts/prerequisites/values.yaml
Fixes https://github.com/datahub-project/datahub/issues/7051
=> fix(mce-consumer): Correct env vars & configure resources for all components

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-frontend/values.yaml
=> expose oidc scope

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/templates/datahub-upgrade/_upgrade.tpl, charts/datahub/templates/kafka-setup-job.yml, charts/datahub/values.yaml
This PR must be merged after https://github.com/datahub-project/datahub/pull/7103/files has been merged into DataHub main repo.
=> fix(kafka-setup): Make kafka setup use explicit topic names

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/templates/hazelcastService.yaml
=> feat(gms): Add hazelcast distributed caching when replica count > 1.0

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/README.md, charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/values.yaml
=> Bump versions v0.10.0

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/values.yaml
=> fix(mce): remove duplicated serviceAccount section

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/values.yaml
Adds checks against MCE & GMS replica counts if managed ingestion is enabled. This is to prevent duplicate ingestion processes situations from happening.
Tested this locally.
=> Add input validation for managed ingestion

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> Update helm charts for datahub 0.10.2 release

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/configmap.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/values.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/values.yaml, charts/datahub/templates/datahub-upgrade/_upgrade.tpl, charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml, charts/datahub/templates/kafka-setup-job.yml, charts/datahub/values.yaml, charts/prerequisites/Chart.yaml, charts/prerequisites/values.yaml
=> feat(search,schema-registry): updates for v0.10.3 release

charts/datahub/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml, charts/datahub/subcharts/acryl-datahub-actions/values.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-frontend/values.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/values.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/values.yaml
=> feat: Add ability to specify extraPodLabels per deployment

charts/datahub/Chart.yaml, charts/datahub/README.md, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/values.yaml
=> Update Default version to v0.10.4

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
=> feat(healthcheck): use new healthcheck endpoint for GMS

charts/datahub/Chart.yaml, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/values.yaml
=> Helm update for 0.10.5 release

charts/datahub/Chart.yaml, charts/datahub/quickstart-values-with-neo4j.yaml, charts/datahub/values.yaml
=> Helm changes for 0.11.0 release

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-ingestion-cron/values.yaml
=> doc(values): remove duplicate doc

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> Default to Datahub v0.12.0

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/values.yaml
=> fix(release): bump chart versions and default cli

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> feat(release): v0.13.0

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> bump(actions): bump actions version

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-frontend/values.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml, charts/datahub/subcharts/datahub-ingestion-cron/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/values.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/values.yaml, charts/datahub/values.yaml
=> updates for release v0.13.1

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/values.yaml
Disable view access permission, still bugs in the implementation around Views
=> disable view access perm

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
=> Add missing env var for values view access controls

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> revert non-blocking update

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> bump hotfix release v0.13.2

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/values.yaml
=> feat(graph): Add environment variable option for disabling introspection

charts/datahub/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/values.yaml
=> Remove unused serviceMonitor option for datahub-actions

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/values.yaml
=> feat(mce): add mce throttling options

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> feat(release): v0.14.0

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/values.yaml
=> feat(mcl-hooks): add configuration for mcl hooks

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> feat(release): release hotfix 0.14.0.2

.github/workflows/release.yaml
=> fix(release): permissions gha

charts/datahub/Chart.yaml
=> Bump chart version

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> bump(actions): bump actions image

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> chore(bump): bump chart for v0.14.1

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/_upgrade.tpl, charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml
=> fix(template-mcp): updates for template-mcps

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/values.yaml
=> feat(throttle): add pending throttling controls for v0.14.2

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml, charts/datahub/values.yaml
=> feat(template-mcps): configure helm revision env

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/_upgrade.tpl, charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml, charts/datahub/values.yaml
bootstrapMCPs
* use default timezone
* use default CLI version
* simplify overrides
=> feat(bootstrapMCPs): follow default globals

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/values.yaml, charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml, charts/datahub/values.yaml
=> feat(v0.15.0): v0.15.0 updates 1

.github/workflows/lint-test.yaml, charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> fix(default-values): add missing setting

charts/datahub/Chart.yaml, charts/datahub/values.yaml, charts/prerequisites/Chart.yaml, charts/prerequisites/values.yaml
=> Helm chart for DataHub release v0.15.0

charts/prerequisites/Chart.yaml, charts/prerequisites/values.yaml
=> Disable schema registry

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/values.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
=> fix(gms): Add global reference to schema registry type

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> bump(release): bump v0.15.0.1

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> bump system-update resources

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/datahub-nocode-migration-job.yml, charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml, charts/datahub/values.yaml
=> feat(restoreIndices): update restore indices available parameters

charts/datahub/Chart.yaml
=> bump Update Chart.yaml

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml, charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml, charts/datahub/values.yaml
=> feat(entityVersioning): add enabled flag for entity versioning feature

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml, charts/datahub/values.schema.json, charts/datahub/values.yaml
=> fix(mae-consumer): prevent accidental misconfiguration causing UI change inconsistencies

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml, charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml
=> fix(mae-consumer): Fix helm syntax usage.

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> docs(search): update search config example

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> update actions pod v0.2.0

charts/datahub/Chart.yaml, charts/datahub/templates/kafka-setup-job.yml
Fix for issue https://github.com/acryldata/datahub-helm/issues/576
=> fix(kafka-setup): #576: Kafka setup job fails when .Values.global.kafka.schemaregistry.type=AWS_GLUE

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/_upgrade.tpl, charts/datahub/templates/datahub-upgrade/datahub-system-update-cron-hourly-job-template.yml, charts/datahub/values.schema.json, charts/datahub/values.yaml
=> feat: add hourly job to tweak ES replica count

charts/datahub/values.yaml
=> warning not to enable hourly cron yet

charts/datahub/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml, charts/datahub/subcharts/acryl-datahub-actions/templates/_helpers.tpl
=> fix(actions-pod): Add missing helper function

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml
=> fix(systemUpdate): quote boolean variable

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-gms/Chart.yaml, charts/datahub/subcharts/datahub-gms/templates/configmap.yaml, charts/datahub/subcharts/datahub-gms/templates/deployment.yaml, charts/datahub/values.schema.json, charts/datahub/values.yaml
Only configure configmap if used
Fallback to application defaults
=> feat(search): custom search application fallback

charts/datahub/Chart.yaml, charts/datahub/values.yaml
=> update default to v1.2.0

charts/datahub/Chart.yaml, charts/datahub/VALUES_REFERENCE.md, charts/datahub/values.yaml
* Added values documentation
* Fix actions chart version
=> update(): bump chart for v1.2.0.1

charts/datahub/Chart.yaml, charts/datahub/templates/datahub-upgrade/_upgrade.tpl
=> feat(system-update): updates to system-update for kafka topic setup

charts/datahub/Chart.yaml, charts/datahub/subcharts/datahub-frontend/Chart.yaml, charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
Add missing PLAY_HTTP_CONTEXT env var to datahub-frontend
=> fix(basepath): add PLAY_HTTP_CONTEXT to datahub-frontend

charts/datahub/Chart.yaml, charts/prerequisites/Chart.yaml, charts/prerequisites/values.yaml
* need to identify community alternatives long-term
=> fix(bitnami): fix bitnami images
