charts/prerequisites/Chart.yaml

Incrementing the version of the neo4j chart to include bug fix on environment variables. 
Setting the environment variables is important to control memory requirements in neo4j, especially when setting resource limits to the pods in kube.

feat (neo4j): bumping neo4j community version

---

charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml

datahub-mae-consumer's ENTITY_REGISTRY_CONFIG_PATH should be under datahub-mae-consumer, not datahub-gms. This PR fixes the above error and redirect to mae-consumer's entity-registry yaml file.

fix(upgrade): typo on mae-consumer ENTITY_REGISTRY_CONFIG_PATH for v0.8.7

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/README.md
charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml
charts/datahub/subcharts/datahub-ingestion-cron/values.yaml

This PR allows the service account name to be specified for crons. This is useful if you have created specific accounts with permissions that are needed to access the metadata (e.g. you might have a Kubernetes Service Account that assumes an IAM Role with access to Glue for a Glue Metadata Cronjob).
I was manually creating my `cronjobs` and then noticed that the chart has this nice capability to specify a bunch of cronjobs which is very convenient. However, I need to be able to specify the service account for each one, as each one has its own specific permissions to the AWS resources it ingests metadata from.
**Request for Comments**
For many of the deployed services (`datahub-mae-consumer`, `datahub-mce-consumer`, etc), you can specify a complete `serviceAccount` object as per the …

feat: support service account name for ingestion

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/config-jmx-exporter.yaml
charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mae-consumer/templates/config-jmx-exporter.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/config-jmx-exporter.yaml

Adding the possibility to define `whitelistObjectNames` and `blacklistObjectNames` for the jmx exporter as documented in [jmx_exporter#configuration](https://github.com/prometheus/jmx_exporter#configuration).
closes: https://github.com/acryldata/datahub-helm/issues/58
For example, the result with the following values:
```
datahub-gms:
enabled: true
image:
repository: linkedin/datahub-gms
tag: "v0.8.17"
exporters:
jmx:
enabled: true
image:
repository: bitnami/jmx-exporter
tag: 0.15.0
pullPolicy: IfNotPresent
config:
lowercaseOutputName: true
whitelistObjectNames:
- "java.lang:type=Runtime"
- "java.lang:type=OperatingSystem"
- "java.lang:type=GarbageCollector,name=*"
- "java.lang:type=Memory"
blacklistObjectNames:
- "kafka.consumer:type=consumer-fetch-manager-metrics,client-id=*"
- …
```

feat: allow to configure whitelistObjectNames and blacklistObjectNames for jmx

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/README.md
charts/datahub/subcharts/datahub-frontend/templates/service.yaml
charts/datahub/subcharts/datahub-frontend/values.yaml
charts/datahub/subcharts/datahub-gms/README.md
charts/datahub/subcharts/datahub-gms/templates/service.yaml
charts/datahub/subcharts/datahub-gms/values.yaml
charts/datahub/subcharts/datahub-mae-consumer/templates/service.yaml
charts/datahub/subcharts/datahub-mae-consumer/values.yaml

Node port is an optional parameter, but it is being hardcoded to a preset port. This may cause collision of ports between different services in the kubernetes cluster. Make it optional, so that k8s can pick the correct port, but keep the capability to set it explicitly if provided.

fix(service): Make nodeport optional

---

charts/prerequisites/Chart.yaml

DataHub is using elasticsearch 7.9.3 which is using vulnerable log4j version.
This PR will upgrade the version of elasticsearch from 7.9.3 to 7.16.2 to avoid log4j vulnerability. https://www.elastic.co/blog/new-elasticsearch-and-logstash-releases-upgrade-apache-log4j2

upgrade elasticsearch to 7.16.2 to avoid apache log4j vulnerability

---

README.md

Old URL 404s - pointing to Metadata Service link.
- [X ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))

Update URL for GMS/metadata service

---

charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml
charts/datahub/templates/elasticsearch-setup-job.yml
charts/datahub/templates/kafka-setup-job.yml
charts/datahub/templates/mysql-setup-job.yml
charts/datahub/values.yaml

Make security context configurable to be able to use the chart on
Openshift, which typically has restrictions on security contexts and do
not allow the previously hardcoded security contexts.
Some comment about the change:
* I separated podSecurityContext and securityContext as that is how it is done in the deployments. 
* I kept the runAsUser and fsGroup for elasticsearchSetupJob, kafkaSetupJob and mysqlSetupJob as those pods runs as root, but not for datahubUpgrade pod as they typically run as user 101 similar to most of the other datahub pods.

fix: Make security context configurable for jobs

---

charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/quickstart-values-with-neo4j.yaml
charts/datahub/subcharts/datahub-gms/README.md
charts/datahub/subcharts/datahub-gms/values.yaml
charts/datahub/values.yaml

Bumping all container versions to latest, 0.8.28.

Helm Charts 0.8.28 Release

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-auth-secrets.yml
charts/datahub/templates/datahub-encryption-secrets.yml
charts/datahub/values.yaml

Helm deletes the secret if told it does not exist. Instead check for the value of the existing secret.

fix(secrets): Fix secret generation logic

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml

When env is not set, it is defaulted to true, so need to make sure it is explicitly set to false if ui_ingestion is not enabled

fix(ui-ingestion): Explicitly set ui ingestion enabled to false when told to do so

---

.gitignore
charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/_helpers.tpl
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/README.md
charts/datahub/subcharts/datahub-gms/templates/_helpers.tpl
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mae-consumer/README.md
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml
charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml
charts/datahub/templates/elasticsearch-setup-job.yml
charts/datahub/templates/kafka-setup-job.yml
charts/datahub/templates/mysql-setup-job.yml
charts/datahub/templates/postgresql-setup-job.yml

This is useful when a K8s cluster requires certain labels to deploy pods. I have tested this on an internal kubernetes instance and it behaves well both when `podLabels` is supplied and when it isn't.
Other changes include migrating to the new ingress API when it becomes available rather then waiting for it to be removed entirely, and some README fixes to the tables.

feat(labels): Add podLabels to Helm charts

---

charts/prerequisites/values.yaml

Fix elasticsearch Readiness probe failed.
Ref: [elastic/helm-charts/elasticsearch: Readiness probe failed: Waiting for elasticsearch cluster to become ready #783](https://github.com/elastic/helm-charts/issues/783)

fix: Fix elasticsearch Readiness probe failed

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/ingress.yaml
charts/datahub/subcharts/datahub-gms/templates/ingress.yaml

The API version change to the ingresses are broken when used with ports that are not numbers. E.g. ALB ingress controller annotations.
Refs: https://github.com/acryldata/datahub-helm/pull/98/files/20521ec9661db7afdb3f9b96dbe53181c62947ad#r831117346
This is my relevant configuration, that worked before on a v1.21 cluster:
```hcl
ingress = {
enabled = true
hosts = [{
host  = local.datahub_fqdn
paths = ["/*"]
redirectPaths = [{
path = "/*"
name = "ssl-redirect"
port = "use-annotation" // <- this is not a number!
}]
}]
annotations = {
"kubernetes.io/ingress.class"            = "alb"
"alb.ingress.kubernetes.io/target-type"  = "ip"
"alb.ingress.kubernetes.io/group.name"   = "internal"
"alb.ingress.kubernetes.io/listen-ports" = jsonencode([{ HTTP = 80 }, { HTTPS = 443 }]) …
```

fix(ingress): fix redirect by annotation on k8s >= 1.19

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/templates/_helpers.tpl
charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml
charts/datahub/templates/_helpers.tpl
charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml

Uses helper methods to detect k8s version being used and changes API spec in CronJob resources accordingly.
Tested locally using minikube with helm dry-runs, cron job warnings no longer appear.

fix(cronjob) Update CronJobs to use stable api in k8s 1.21

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-gms/values.yaml
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml

This PR is to add JMX port for MCE deployment which was missing.
When working on exposing JMX metrics, I think we cannot assume that everyone will be using prometheus exporter?
Hence I added `enableJMXPort` , happy to discuss or remove it.
In my case I was using Datadog, which has a direct JMX integration. 
Let me know what I need to change too. Thanks
Will be happy to add this as a comment as well, so that developers will be onboarded faster.
>       - name: JMX_OPTS
>         value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=4318 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

fix(deployment): added jmx port for mce deployment, jmx only

---

charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/quickstart-values-with-neo4j.yaml
charts/datahub/subcharts/datahub-gms/README.md
charts/datahub/values.yaml

0.8.34 is yanked https://pypi.org/project/acryl-datahub/0.8.34/ We should not be using that.

fix: remove yanked cli as default

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-gms/values.yaml
charts/datahub/templates/datahub-auth-secrets.yml
charts/datahub/values.yaml

This PR adds a salt configuration to our helm deployment which is necessary for revokable token feature from PR: https://github.com/datahub-project/datahub/pull/4970

feat(security): Adds salt configs for revokable tokens

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-auth-secrets.yml

A missing "token_service_salt" key in an existing "datahub-auth-secrets" secret (which was introduced with PR #118) causes a failed upgrade: `Error: UPGRADE FAILED: error validating "": error validating data: unknown object type "nil" in Secret.data.token_service_salt`
This PR fixes this problem by generating a new salt when the key is not already set in the existing secret.

fix(security): generate a new token_service_salt if it is not set in the existing secret

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml
charts/datahub/subcharts/acryl-datahub-actions/values.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml

Title says it. 
- Enable PE consumer in gms pod / mae consumer pod 
- Migrate to new DataHub Actions container

Enable PE consumer + migrate to DataHub Actions Container

---

charts/datahub/README.md

When using postgresqlSetupJob the database host has to be specified in `values.yaml`.  The necessary field, `global.sql.datasource. hostForPostgresqlClient`, was missing from README.md.

docs: add missing docs for defining host for postgresqlSetupJob

---

charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/README.md
charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml
charts/datahub/subcharts/datahub-ingestion-cron/values.yaml
charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-upgrade-job.yml
charts/datahub/templates/elasticsearch-setup-job.yml
charts/datahub/templates/kafka-setup-job.yml
charts/datahub/templates/mysql-setup-job.yml
charts/datahub/templates/postgresql-setup-job.yml
charts/datahub/values.yaml

Adds an option to add `podAnnotations` to jobs. The style is the same as with `deployments` e.g. here https://github.com/acryldata/datahub-helm/blob/21d4f781d7b0cb276a3e6bf076ebeaafabc5b48c/charts/datahub/subcharts/datahub-gms/templates/deployment.yaml#L12-L17
Motivation:
- adding [vault annotations](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/annotations/) to inject secrets from vault - many jobs require some sort of connection string, that may be usually stored in vault
- adding [datadog annotations](https://docs.datadoghq.com/agent/kubernetes/integrations/?tab=kubernetes#configuration) to configure log collection
- Tested my changes locally with `helm template charts/datahub -f charts/datahub/values.yaml`
- Tried adding annotations to `charts/datahub/values.yaml` and …

Option to add podAnnotations to jobs.

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml

When `.Values.global.datahub.monitoring.enablePrometheus` is set to true, GMS and MAE deployments get a JMX port opened and `ENABLE_PROMETHEUS` set, but MCE deployment only gets the port. I assume it's a mistake and I'm adding this variable to MCE.

fix(metrics): fix Prometheus env variable in the MCE consumer deployment

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
charts/datahub/subcharts/datahub-frontend/values.yaml

This PR adds a lifecycle node to the datahub-frontend deployment template.
It can be used to execute lifecycle hooks, e.g. postStart actions, like
replacing the default user.props file.

feat(datahub-frontend): Allow lifecycle hooks

---

charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/values.yaml

This PR adds the ability for end-users to specify resource requests and limits
for the datahub upgrade job 'restore indices'. This is needed for situations
where the restore indices job will OOM due to a large backfill of data. I've
seen this happening with our deployment of datahub and am unable to tune
the resources for the restore indices job because the current requests
and limits are hard-coded.
In addition, bumps chart version to 0.2.90

feat(datahub-upgrade): Restore Indices Resources

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/README.md
charts/datahub/subcharts/datahub-frontend/templates/ingress.yaml
charts/datahub/subcharts/datahub-frontend/values.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/README.md
charts/datahub/subcharts/datahub-gms/templates/ingress.yaml
charts/datahub/subcharts/datahub-gms/values.yaml

Added support for providing extra labels for ingress configuration in datahub-gms and datahub-frontend sub-charts. Updated README files. This change resolves issue #162 
This is a minor and non-intrusive change
- [ x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ x] Links to related issues (if applicable)
- [x ] Docs related to the changes have been added/updated (if applicable)

feat: add extra labels to ingress configurations

---

charts/datahub/Chart.yaml
charts/datahub/values.yaml
charts/prerequisites/Chart.yaml
charts/prerequisites/values.yaml

This PR adds the postgresql chart from the Bitnami chart repository as an optional and by default disabled dependency to the prerequisites Helm chart. Additionally I have added some example configuration to the values.yaml of the datahub Helm chart for documentation purposes (as far as I know the usage of PostgreSQL is not documented anywhere, as I had to search the repository for the [correct values](https://github.com/datahub-project/datahub/blob/master/docker/datahub-gms/env/docker.postgres.env) etc.).
I am not sure if this should be part of the official Helm charts, but as I wanted to use PostgreSQL in my local deployment and I already changed the charts accordingly, maybe others also want to use it and do not want to do the work twice.
If this PR is merged, we could also add some …

feat(prerequisites): add postgresql to prerequistes Helm chart as an optional dependency

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/README.md
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
charts/datahub/subcharts/datahub-frontend/values.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/README.md
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-gms/values.yaml
charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mae-consumer/README.md
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mae-consumer/values.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/README.md
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mce-consumer/values.yaml

This PR adds the ability for end-users to configure `revisitonHistoryLimit` for the deployments of subcharts.
In addition, bumps chart version to 0.2.96

feat(charts): add an option to configure revisionHistoryLimit to subcharts

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/README.md
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
charts/datahub/subcharts/datahub-frontend/values.yaml

This PR adds an option to configure OIDC authentication client secret to refer to Kubernetes Secrets. The deployment YAML will retrieve `AUTH_OIDC_CLIENT_SECRET` from Kubernetes Secrets if `datahub-frontend.oidcAuthentication.clientSecretRef` is present.
This implementation is also backward compatible with the existing `datahub-frontend.oidcAuthentication` config.
Local testing has been done through rendering using `helm template . > preview.yaml.`

feat: datahub-frontend add oidc authentication client secret reference

---

charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml

This PR introduces a general way for passing SSL secrets needed for some ingestion sources such as MySQL when the `require_secure_transport` flag is on. Because MySQL driver requires the SSL certificates to be in files, we cannot easily use env vars to do this without modifying `datahub-actions`.
This approach uses a customer created k8s secret and then mount the secret as a volume in the `datahub-actions` container. Because when a k8s secret is mounted as a volume, [each key name is automatically mounted as a file on the mount path](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod), we can easily refer to these certificate/key files in the ingestion recipe.
Below is an example of how this works for ingestion from a MySQL instance that is …

Mount a customer defined k8s secret for ssl secrets needed in ingestion recipes

---

charts/datahub/Chart.yaml
charts/datahub/quickstart-values-with-neo4j.yaml
charts/datahub/values.yaml

- Bumping the pinned version of datahub-actions to be compatible with v0.8.44 frontend containers.

fix(): New helm charts version with compatible datahub-actions version

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/_upgrade.tpl

Adds system auth credentials to datahub upgrade jobs. This is used to set GMS to read-only mode for upgrade processes.

fix(datahub-upgrade): Add system auth credentials to datahub upgrade jobs

---

charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/templates/mysql-setup-job.yml
charts/datahub/templates/postgresql-setup-job.yml
charts/datahub/values.yaml

This PR extends the existing configuration for the SQL database in two ways:
1. Allows the SQL set-up jobs to run using a different username and password to that used by the GMS. This allows users to specify a login account with a more permissive set of permissions for the set-up jobs (which requires essentially owner perms) than the logic account used by the GMS (which only requires traditional read-write perms).
2. Allows specifying the login password for the SQL backings using a string value. This is specifically important for users interacting with vault manipulating webhooks to inject their vault-saved credentials, which doesn't pair nicely with using k8s secrets.
This PR is backwards compatible to existing configuration approach (importantly not changing any of the default values). …

feat(sql): extend sql username/password configuration

---

charts/prerequisites/values.yaml

Added information about the key name in the secret, or it will fail like this:
Error: couldn't find key neo4j-password in Secret default/neo4j-secrets

docs: add secret key information

---

charts/datahub/Chart.yaml
charts/datahub/values.yaml

`global.elasticsearch.useSSL` isn't documented in `values.yaml`.

Document global.elasticsearch.useSSL in values.yaml

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/_upgrade.tpl

The secret which is referensed by `DATAHUB_SYSTEM_CLIENT_SECRET` in `charts/datahub/templates/datahub-upgrade/_upgrade.tpl` can only be expected to be present when `global.datahub.metadata_service_authentication.enabled = true`.  Fixes bug introduced in #199.

fix: only add DATAHUB_SYSTEM_CLIENT envs when metadata service auth enabled

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml

This a possible fix for #200. The template `common.tplvalues.render` in https://artifacthub.io/packages/helm/bitnami/common?modal=template&template=_tplvalues.tpl handle templates too, but this versions is more simple...

fix: make hostAliases work in datahub-ingestion-cron

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/_upgrade.tpl

The datahub-upgrade job is looking for a `mysql-secret` even if `global.sql.datasource.password.value` is set.

bugfix: datahub-upgrade use datasource password value if set

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/values.yaml
charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mae-consumer/values.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/values.yaml

Complementary PR for https://github.com/acryldata/datahub-helm/pull/214

fix: move default tag to global in subcharts

---

.github/workflows/release.yaml
charts/datahub/Chart.yaml
charts/datahub/values.yaml

fix(release): Revert workflow change & change upgrade job to 0.9.3

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/values.yaml

config(gms): enable elasticsearch reindex by default

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml

fix(restore-indices): restore indices should use global datastore values

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/_upgrade.tpl
charts/datahub/values.yaml

Currently I am trying to deploy datahub with helmfile and I am doing multiple tests and recreating namespaces and changing environments, I don't want to manually create a neo4j secret each deployment, and I don't believe it should be forced.
This feature will let me create a simple value config to be able to deploy without thinking of creating secrets previously.

feat(neo4j-password): be able to deploy without neo4j secret

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/README.md
charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml
charts/datahub/subcharts/acryl-datahub-actions/values.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/README.md
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
charts/datahub/subcharts/datahub-frontend/values.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/README.md
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-gms/values.yaml
charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mae-consumer/README.md
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mae-consumer/values.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/README.md
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mce-consumer/values.yaml

Services such as Datadog require additional labels to be set on the `Deployment` resource (see for example [here](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes#full-configuration)). This PR adds support for specifying additional labels on the `Deployment` resource in:
- datahub-gms
- datahub-frontend
- datahub-mae-consumer
- datahub-mce-consumer
- acryl-datahub-actions

feat: allow extra labels on deployments

---

charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml
charts/datahub/templates/datahub-upgrade/_upgrade.tpl
charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml
charts/datahub/templates/elasticsearch-setup-job.yml

Fixes #262. Allows users to put passwords in the following format:
```
elasticsearch:
auth:
username: abc123
password:
value: es-plaintextpassword
```

feat(elasticsearch): allow plain text password

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/_upgrade.tpl
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml

Fixes: [#261](https://github.com/acryldata/datahub-helm/issues/261)

fix: remove duplicated EBEAN env vars on datahub-upgrade jobs

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/templates/serviceaccount.yaml

The `acryl-datahub-actions` subchart offers an option to create a service account:
https://github.com/acryldata/datahub-helm/blob/25fd3c5cc7a8885a0c1bf6958bdbd4549e9771a3/charts/datahub/subcharts/acryl-datahub-actions/values.yaml#L15-L22
but the implementation is missing. This PR adds the `serviceAccount` template.

fix: add missing service account in acryl-datahub-actions

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml

Fixes: [https://github.com/acryldata/datahub-helm/issues/261](https://github.com/acryldata/datahub-helm/issues/261)
More duplicate env variables than just `EBEAN_*` are reported. This PR will remove any others left here after patch #269

fix: remove duplicated EBEAN env vars on datahub-upgrade jobs (#269)

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-auth-secrets.yml
charts/datahub/values.yaml

- Bumps chart datahub version to 0.10.1 to match latest release 
- Makes `datahub-auth-secrets` creation dependant on whether metadata service authentication has been enabled or not.

Release Charts for DataHub v0.10.1

---

charts/datahub/Chart.yaml
charts/datahub/values.yaml

Updated correct `secretKey` from `datahub-auth-secrets` for `systemClientSecret` in values.yaml file reported in #279 
Updated Chart version

fix: secretkey for systemClientSecret in values.yaml file

---

README.md
charts/prerequisites/Chart.yaml
charts/prerequisites/values.yaml

Our dependencies chart is setup to use 3 ES nodes in 3 AZ-equivalents, but is broadly intended for use as a test harness which often runs in single-node events.
So let's fix this and have it be single-node by default

Draft: feat(PFP-102): Make Elasticsearch use 1 master node by default

---

charts/datahub/values.yaml

1. Found and fixed an issue during rollout (PSQL db in connection string ignoring during rollout and PSQL setup job creates "datahub" database instead specific, also failed dataHub upgrade job).
2. Added value for elastic search index prefix (already present in helm chart).
All are checked in local env (minikube) and with AWS-managed services.

feat: values for PSQL db name, elastic prefix

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-nocode-migration-job.yml
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml
charts/datahub/templates/elasticsearch-setup-job.yml
charts/datahub/templates/kafka-setup-job.yml
charts/datahub/templates/mysql-setup-job.yml
charts/datahub/templates/postgresql-setup-job.yml

Instead of specifying the labels for `(Cron)Jobs` individually, use the set of predefined labels from `datahub.labels`. In addition to the DRYing up the code, this also makes sure the `helm.sh/chart` label has a valid value, see: https://github.com/acryldata/datahub-helm/blob/e9fecf7fe203a7eb7bf41821afe78c1c90ce83eb/charts/datahub/templates/_helpers.tpl#L31

fix: use common labels for (Cron)Jobs

---

charts/datahub/Chart.yaml
charts/datahub/README.md
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml
charts/datahub/templates/datahub-upgrade/_upgrade.tpl

Re-opening, I had submitted a similar one earlier that I closed when I realized I broke existing syntax for specifying plain usernames, this time I tested it both ways.
Our storage team manages and distributes both our username and password via secrets, which led us to introduce this patch on our end. It would be great if we can get it merged into the project, let me know if you need me to add anything

feat: allow pulling ebean username from secrets alongside password

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-auth-secrets.yml
charts/datahub/templates/datahub-encryption-secrets.yml

This is enabling (we could say even fix 😅 ) the support for configurable `secretRef` here https://github.com/acryldata/datahub-helm/blob/3678c86f5c925662828442f405b5b2e769c960d2/charts/datahub/values.yaml#L526

chore(secrets): use configurable refs instead of fixed names

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-auth-secrets.yml
charts/datahub/templates/datahub-encryption-secrets.yml
charts/datahub/templates/datahub-upgrade/datahub-nocode-migration-job.yml
charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml
charts/datahub/templates/elasticsearch-setup-job.yml
charts/datahub/templates/kafka-setup-job.yml
charts/datahub/templates/mysql-setup-job.yml
charts/datahub/templates/postgresql-setup-job.yml
charts/datahub/values.yaml

The use of pre-install hooks can be problematic when resources need to be available before the hooks run, but can't be safely destroyed and recreated (like secrets). We are using the helm chart as a dependency in our chart which also deploys a postgres database using the postgres operator. Since it isn't possible to deploy the database as a hook as either you would never be able to update it or it will get destroyed and recreated on upgrades, we need the ability to change the hook annotations for the setup and migration jobs. This would allow us to run the jobs as `post-install` hooks, along with init containers that will wait until the database is ready for connections.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- …

feat: allow for overriding job annotations and adding init containers

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml
charts/datahub/subcharts/datahub-ingestion-cron/values.yaml

This PR enabling to users to set up different parameters of the cronjob/job in the ingestion process. In particular, we will be able to configure the following parameters:
- `concurrencyPolicy`
- `successfulJobsHistoryLimit `
- `failedJobsHistoryLimit `
- `backoffLimit `
- `restartPolicy`

feat(cron): Adding more parameters to ingestion-cron

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml
charts/datahub/values.yaml

There are 3 new env variable flags that relate to the new unified search and browse experience that I'm adding to our helm charts here. The new unified search and browse experience goes out with the v0.10.5 release so these variables are necessary to get in for folks.

Update charts to include search and browse env variable flags

---

charts/datahub/Chart.yaml
charts/datahub/values.yaml

Sets search and browse flags off by default so we can button other things up first.

fix(config) Set search and browse flags default off

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml
charts/datahub/subcharts/datahub-ingestion-cron/values.yaml

This PR enable users to configure  nodeselector, tolerations and affinity capabilities for each cron job in the datahub-ingestion-cron helm chart.

feat(cron): support nodeselector, affinity and toleration capabilities 

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml

Resolves: #347 
I think this should be true to solve the following error:
```log
2023-08-28 01:50:42,180 [main] ERROR c.l.d.u.s.e.steps.DataHubStartupStep:40 - DataHubStartupStep failed.
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.io.IOException: No schema registered under subject!
at io.confluent.kafka.schemaregistry.client.MockSchemaRegistryClient.getLatestVersion(MockSchemaRegistryClient.java:261)
at io.confluent.kafka.schemaregistry.client.MockSchemaRegistryClient.getLatestSchemaMetadata(MockSchemaRegistryClient.java:310)
at io.confluent.kafka.serializers.AbstractKafkaSchemaSerDe.lookupLatestVersion(AbstractKafkaSchemaSerDe.java:181)
at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSer …
```

fix(datahub-system-update-job): enable `SPRING_KAFKA_PROPERTIES_AUTO_REGISTER_SCHEMAS`

---

charts/datahub/subcharts/datahub-gms/values.yaml
charts/datahub/values.yaml

I have some issue with datahub-gms:
```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
Caused by: java.net.ConnectException: Connection refused
```
```
Warning  Unhealthy  4m31s (x12 over 8m1s)  kubelet            Readiness probe failed: Get "http://10.18.64.5:8080/health": dial tcp 10.18.64.5:8080: connect: connection refused
Normal   Killing    4m31s                  kubelet            Container datahub-gms failed liveness probe, will be restarted
Warning  Unhealthy  3m1s (x9 over 8m1s)    kubelet            Liveness probe failed: Get "http://10.18.64.5:8080/health": dial tcp 10.18.64.5:8080: connect: connection refused
```
```
ERROR: Cannot connect to GMSat http://host/ datahub-datahub-gms port 8080. Make sure GMS is …
```

chore(gms): setup readiness & liveness from main chart

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/secrets.yaml

Improves the default security of a non-specified randomly generated key for clusters.

fix(secret): improve secret default behavior

---

.github/workflows/release.yaml
README.md
charts/datahub/Chart.yaml
charts/datahub/quickstart-values-with-neo4j.yaml
charts/datahub/values.yaml
charts/prerequisites/Chart.yaml
charts/prerequisites/values.yaml

Update neo4j to the latest chart version supplied by the neo4j organisation. The new chart offers build in support for enterprise and comunity deployments. This also improves security by exposing the podSecurityContext and containerSecurityContext to the user.
BREAKING CHANGE:
Removal of neo4j-comunity chart and values
Change neo4j parameters are now under neo4j.neo4j
Rename neo4jPassword to password
Rename existingPasswordSecret to passwordFromSecret Change passwordFromSecret expects: neo4j-password and NEO4J_AUTH keys Require PersistentVolume from values
Closes: https://github.com/acryldata/datahub-helm/issues/364

feat(neo4j): update neo4j chart

---

charts/prerequisites/Chart.yaml

This MR fixes used kafka helm chart due to error when using kraft and helm drift detection
related issue: https://github.com/acryldata/datahub-helm/issues/377

fix(kafka): increase kafka chart version due to kraft enabled error

---

charts/datahub/subcharts/datahub-ingestion-cron/values.yaml

This PR fixes issue mentioned at https://github.com/acryldata/datahub-helm/issues/389 .The duplicate shell command is removed from values.yaml since it is already present in cron.yaml template. Thanks @jimsmith for reporting and figuring out the root cause.

fix(ingestion-cron): remove duplicate shell command in cron chart

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
charts/datahub/subcharts/datahub-frontend/values.yaml

This change would make the containerPort configurable via values instead of directly hard-coding it.

(feat) configuring containerPort from Values in datahub-frontend

---

charts/datahub/Chart.yaml
charts/datahub/templates/mysql-setup-job.yml
charts/datahub/templates/postgresql-setup-job.yml

This adds the functionality from #291 to the MySQL and PostgreSQL setup jobs

feat(sql): allow providing username from secret for sql setup jobs

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml

This annotation will cause the Deployment to automatically restart the pod if the users secret is updated. Without this annotation, the pod might be outdated, having an internal version of `user.props` that doesn't match the secret's.

feat(datahub-frontend): add checksum annotation for user-secrets

---

charts/datahub/values.yaml

For Using Confluent Kafka (Schema Registry), We have to set 2 values.
* basic.auth.credentials.source -> USER_INFO
* basic.auth.user.info
If we do not fill in these two values, we cannot input any information such as Ingestion even though the kafkasetup job was successful. 
```
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Unauthorized; error code: 401
```
So I think It is confused, so I think it should be written into the default values. Thanks!

Feat: Add Basic Auth For Using Confluent Kafka Schema Registry API

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml

Fix Issue https://github.com/acryldata/datahub-helm/issues/414 where only google OIDC Username claim and regexp were overridable. This was incorrect, and should have never been the case, this is especially important for azure since some Entra ID deployments do not specify email addresses in the OIDC token.

Fix OIDC username claim not overridable for azure

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml
charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml
charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-nocode-migration-job.yml
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml
charts/datahub/templates/elasticsearch-setup-job.yml
charts/datahub/templates/kafka-setup-job.yml
charts/datahub/templates/mysql-setup-job.yml
charts/datahub/templates/postgresql-setup-job.yml

Allow `nodeSelector` and `tolerations` to be applied to all Datahub components globally. Any global defaults can be overridden on each subchart individually.

Allow nodeSelector and tolerations to be applied to all components globally

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml

Fix bug introduced in #421
Because we're in a `range` inside `datahub-ingestion-cron`, we can't access global values via `{{ .Values.global...` Instead, we need `{{ $.Values...`.  Otherwise, we get an error:
```
Error: template: datahub/charts/datahub-ingestion-cron/templates/cron.yaml:78:34: executing "datahub/charts/datahub-ingestion-cron/templates/cron.yaml" at <.Values.global.nodeSelector>: nil pointer evaluating interface {}.global
helm.go:84: [debug] template: datahub/charts/datahub-ingestion-cron/templates/cron.yaml:78:34: executing "datahub/charts/datahub-ingestion-cron/templates/cron.yaml" at <.Values.global.nodeSelector>: nil pointer evaluating interface {}.global
```
Fix so that it uses globals or the cron specific `nodeSelector` and `tolerations` instead of triggering a nil …

fix(ingestion): Fix scope of `.Values.globals` in ingestion

---

charts/datahub/Chart.yaml
charts/datahub/templates/kafka-setup-job.yml

Newer Kafka versions no longer depend on ZooKeeper, therefore allow `global.kafka.zookeeper.server` to be unset.

fix(kafka-setup-job): allow global.kafka.zookeeper.server to be unset

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/templates/configmap.yaml

api version should be `v1` for configmap objects, not `batch/v1`.

fix: fix bug in configmap api version

---

charts/prerequisites/Chart.yaml
charts/prerequisites/values.yaml

Start MySQL with the character-set and collation required by Datahub.

fix(mysql): adjust default character set and collation

---

charts/prerequisites/Chart.yaml
charts/prerequisites/values.yaml

Most of the changes address the major change to the Kafka chart in `24.0.0`. See below for reference.
https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2400
1. The chart now has two statefulsets and their settings fall under the `controller` and `broker` section respectively. 
2. The default `replicaCount` for `controller` is `1` and for `broker` is `0`. So we need to override them
3. The default protocol for client and inter broker listeners are both `SASL_PLAINTEXT`. So we need to override them to `PLAINTEXT` to be backward compatible
4. Many of the server properties are no longer exposed as chart parameters and need to be passed in via the `extraConfig` parameter.
Testing: 
1. Deployed a brand new install of prerequisites and datahub chart in a GKE cluster. All components …

Bump kafka chart to 26.11.2 that uses kafka 3.6.1

---

charts/prerequisites/Chart.yaml

Newer versions of the mysql chart require the `mysql-password` key to exist in the existing secret. In order to allow for a transition period (and update existing documentation), this rollbacks the version before the breaking change in the mysql chart.

fix(mysql): downgrade mysql chart to 9.4.9

---

README.md

By the change of mysql helm chart version the provided secret must contain at least three keys:
- mysql-root-password
- mysql-replication-password
- mysql-password
Otherwise mysql chart won't install.
More information: https://artifacthub.io/packages/helm/bitnami/mysql#mysql-common-parameters

docs: Updated mysql secret generation command

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/hazelcastService.yaml

`\W` is equivalent to `[^a-zA-Z0-9_]`, which prevents `_` to be replaced. However, as reported in PR #386 , `_` is not a valid character. Some recent refactors introduced back the issue, so fixing again.

fix: hazelcast service name

---

charts/datahub/Chart.yaml
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/values.yaml

* and set the default schedule to once per week on Sunday
Issue with the previous schedule `* * * * *` is that one pod gets started every minute when the job execution is triggered via the command in the [restore indices doc](https://datahubproject.io/docs/how/restore-indices/#kubernetes):
```bash
kubectl create job --from=cronjob/datahub-datahub-restore-indices-job-template datahub-restore-indices-adhoc
```
When the pod takes longer to run, more pods are started and continue to pile up in greater amount, causing resource issues in Kafka and in the Kubernetes cluster.
- ~~[] Links to related issues (if applicable)~~
- ~~[] Tests for the changes have been added/updated (if applicable)~~

feat(restoreIndices): configurable crontab schedule

---

charts/prerequisites/values.yaml

To be able to use the GCloud SQL Proxy with IAM authentication we want to specify a certain serviceAccount that has the needed IAM permissions

feat[prerequisites]: serviceAccount for gcloud-sqlproxy

---

charts/datahub/Chart.yaml
charts/datahub/values.yaml
charts/prerequisites/Chart.yaml
charts/prerequisites/values.yaml

As the OpenSearch client libraries are already used for some time and as there will be probably no support for Elasticsearch 8+ "soon" (see also: https://datahubspace.slack.com/archives/CV2KB471C/p1706027299777929?thread_ts=1703747966.285459&cid=CV2KB471C) it is probably time to also have the OpenSearch Helm chart as part of the prerequisites chart (at least as an optional dependency).
To have a similar configuration as Elasticsearch some default configuration is necessary (e.g. in OpenSearch security is enabled by default).
I have used the latest version for the OpenSearch chart (2.18.0), however in the default configuration the tag for the image is overwritten to version 2.11.0 - this is exactly the version which is used as part of the [Docker Compose …

feat(prerequisites): add optional OpenSearch chart with default configuration

---

charts/prerequisites/Chart.yaml
charts/prerequisites/values.yaml

The default mysql image tag for the `bitnami/mysql` chart version `9.4.9` only supports `linux/amd64`. This change updates the tag to the latest [8.0.32-debian-11](https://hub.docker.com/layers/bitnami/mysql/8.0.32-debian-11-r26/images/sha256-fe61e6d10c4bbfc0c010fac1dd1d6ca808943246142efa08cc7bb07f6a928c2c?context=explore) release which additionally supports `linux/arm64`.
Fixes issue #481

fix(mysql): update mysql image tag

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/Chart.yaml
charts/datahub/subcharts/acryl-datahub-actions/values.yaml
charts/datahub/subcharts/datahub-frontend/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml
charts/datahub/subcharts/datahub-frontend/values.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
charts/datahub/subcharts/datahub-gms/templates/hazelcastService.yaml
charts/datahub/subcharts/datahub-gms/values.yaml
charts/datahub/subcharts/datahub-ingestion-cron/Chart.yaml
charts/datahub/subcharts/datahub-ingestion-cron/templates/cron.yaml
charts/datahub/subcharts/datahub-mae-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mae-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mae-consumer/values.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml
charts/datahub/subcharts/datahub-mce-consumer/values.yaml
charts/datahub/templates/datahub-upgrade/datahub-cleanup-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-nocode-migration-job.yml
charts/datahub/templates/datahub-upgrade/datahub-restore-indices-job-template.yml
charts/datahub/templates/datahub-upgrade/datahub-system-update-job.yml
charts/datahub/templates/elasticsearch-setup-job.yml
charts/datahub/templates/mysql-setup-job.yml
charts/datahub/templates/postgresql-setup-job.yml

To make it a bit more transparent - I was not aware of it - that there are parts of the REST API which are not secured by default (of course you have to be authenticated, but each authenticated user is authorized by default to use these endpoints), this PR adds a new configuration option similar to the view authorization which allows to enable REST API authorizations. Technically this is already possible today using extra environment variables - the intention here is only to make it more transparent.
As the REST API authorizations were not enabled by default in the past (and are [not enabled by default](https://github.com/datahub-project/datahub/blob/6fdf2f73540a46369dd6636411ae960a6812c110/metadata-service/configuration/src/main/resources/application.yaml#L47) in the metadata-service …

feat: add configuration option to enable REST API authorizations

---

charts/prerequisites/values.yaml

This small change fixes a likely typo referencing the wrong secret name (extra "n") and cleans it up with commas.

docs: fix comment referencing secrets to create

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-frontend/templates/ingress.yaml
charts/datahub/subcharts/datahub-frontend/values.yaml
charts/datahub/subcharts/datahub-gms/templates/ingress.yaml
charts/datahub/subcharts/datahub-gms/values.yaml

k8s supports different values for `pathType` for ingresses, as [documented here](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types). Make the ingress pathType configurable for the gms and frontend charts so that users can set different values based on their ingress deployment strategy.

feat(ingress): make ingress pathType configurable

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/Chart.yaml
charts/datahub/subcharts/datahub-mce-consumer/templates/deployment.yaml

Although the MCE consumer is not consuming any topic using the consumer group ID of the MAE consumer (which would make no sense), it seems the MCE consumer needs the consumer group ID used by the MAE consumer for the [KafkaThrottleFactory](https://github.com/datahub-project/datahub/blob/7761394d68926f76df4991b0dfadb0e0694aef08/metadata-service/factories/src/main/java/com/linkedin/gms/factory/kafka/throttle/KafkaThrottleFactory.java#L28) - I think this is something new and wasn't there half a year ago.
FYI @RyanHolstien: I am tagging you here because you merged my original PR #436 - I hope we can have this fix merged a bit sooner and don't have to wait almost half a year (or more than half a year?)...😅

fix(mce-consumer): add METADATA_CHANGE_LOG_KAFKA_CONSUMER_GROUP_ID environment variable to MCE consumer.

---

charts/datahub/Chart.yaml
charts/datahub/values.schema.json

Helm chart template is already setup to allow fetching global.sql.datasource.username from k8s secrets, but the json validator schema blocks it. This update fixes json schema
stale issue: https://github.com/acryldata/datahub-helm/issues/531
partially duplicate of this stale PR: https://github.com/acryldata/datahub-helm/pull/586
readme is already okay: https://github.com/acryldata/datahub-helm/blob/de3ba01544aba58c95de7e4a611648884b9bf677/charts/datahub/README.md?plain=1#L159-L161

fix: let username be an object in json schema

---

charts/datahub/Chart.yaml
charts/datahub/subcharts/datahub-gms/Chart.yaml
charts/datahub/subcharts/datahub-gms/templates/service.yaml
charts/datahub/values.schema.json
charts/datahub/values.yaml

allows setting the `loadBalancerClass` property on the datahub-gms service. Useful when
using EKS Auto Mode as it does not support setting the
`service.beta.kubernetes.io/aws-load-balancer-type` annotation.

feat(datahub-gms): add ability to specify load balancer class
